#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: agent (NestJS + Prisma + PostgreSQL)
# Generator version: init-dev-server@1
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.

set -euo pipefail

# Bash version guard
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required; found ${BASH_VERSION}" >&2
  exit 127
fi

# D-11.4: tee stdout/stderr to /tmp/pivota-dev.log
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: agent/nestjs-prisma-postgres)"

# D-11.1 + D-11.2: NestJS binds to PORT env var (0.0.0.0 is default in main.ts)
export PORT="${PORT:-3000}"
export HOST="${HOST:-0.0.0.0}"

# D-11.3: .env.example -> .env transitional copy
if [[ ! -f .env && -f .env.example ]]; then
  echo "[pivota] copying .env.example -> .env"
  cp .env.example .env
fi

# Override DATABASE_URL from environment (native-sidecar mode: Postgres on localhost:5432)
if [[ -n "${DATABASE_URL:-}" ]]; then
  echo "[pivota] DATABASE_URL from environment: ${DATABASE_URL}"
  # Update .env with the injected DATABASE_URL
  if [[ -f .env ]]; then
    sed -i "s|^DATABASE_URL=.*|DATABASE_URL=${DATABASE_URL}|" .env
  fi
fi

# D-12: idempotent install via lockfile hash + presence check
SENTINEL="/tmp/pivota-setup-sentinel"
LOCK_FILE_PATH="package-lock.json"
INSTALL_PRESENCE_CHECK="node_modules/.package-lock.json"
INSTALL_CMD='npm ci --prefer-offline 2>/dev/null || npm install'

run_install() {
  echo "[pivota] running install: $INSTALL_CMD"
  bash -c "$INSTALL_CMD"
  # After install, generate Prisma client
  echo "[pivota] generating Prisma client"
  npx prisma generate
}

if [[ -n "$LOCK_FILE_PATH" && -f "$LOCK_FILE_PATH" ]]; then
  CURRENT_HASH=$(sha256sum "$LOCK_FILE_PATH" | cut -d' ' -f1)
  PREVIOUS_HASH=$(cat "$SENTINEL" 2>/dev/null || echo "")
  PRESENCE_OK=1
  if [[ -n "$INSTALL_PRESENCE_CHECK" && ! -e "$INSTALL_PRESENCE_CHECK" ]]; then
    PRESENCE_OK=0
  fi
  if [[ "$CURRENT_HASH" == "$PREVIOUS_HASH" && "$PRESENCE_OK" == "1" ]]; then
    echo "[pivota] lockfile unchanged AND install output present; skipping install"
  else
    run_install
    echo "$CURRENT_HASH" > "$SENTINEL"
  fi
elif [[ -n "$INSTALL_CMD" ]]; then
  if [[ ! -f "$SENTINEL" ]]; then
    run_install
    touch "$SENTINEL"
  fi
fi

# Run Prisma migrations before starting (idempotent, native-sidecar mode)
echo "[pivota] running Prisma migrate deploy"
npx prisma migrate deploy 2>/dev/null || echo "[pivota] migrate deploy skipped (no migrations dir yet)"

# Apply schema.sql directly if migrations not yet set up
if [[ -f "prisma/schema.sql" ]]; then
  echo "[pivota] applying schema.sql via psql"
  PGPASSWORD="$(echo "${DATABASE_URL}" | sed -n 's|.*://[^:]*:\([^@]*\)@.*|\1|p')" \
  psql "${DATABASE_URL}" -f prisma/schema.sql 2>/dev/null || echo "[pivota] schema.sql apply skipped (already applied or psql unavailable)"
fi

# Apply reference data seed if available
if [[ -f "scripts/seed-reference-data.sql" ]]; then
  echo "[pivota] applying reference data seed"
  psql "${DATABASE_URL:-postgres://postgres:devpass@localhost:5432/app}" -f scripts/seed-reference-data.sql 2>/dev/null || echo "[pivota] seed skipped"
fi

# Build the NestJS app
echo "[pivota] building NestJS app"
npm run build

# D-14: retry loop (3 attempts, exponential backoff)
EXEC_CMD='npm run start'
ATTEMPT=1
DELAY=1
while (( ATTEMPT <= 3 )); do
  echo "[pivota] attempt $ATTEMPT: $EXEC_CMD"
  if bash -c "$EXEC_CMD"; then
    echo "[pivota] inner command exited 0; propagating success"
    exit 0
  fi
  EXIT_CODE=$?
  if (( ATTEMPT == 3 )); then
    echo "[pivota] all 3 attempts failed (last exit=$EXIT_CODE); surfacing failure"
    exit "$EXIT_CODE"
  fi
  echo "[pivota] attempt $ATTEMPT failed (exit=$EXIT_CODE); retrying in ${DELAY}s"
  sleep "$DELAY"
  DELAY=$(( DELAY * 2 ))
  ATTEMPT=$(( ATTEMPT + 1 ))
done

exit 1
# === END PIVOTA PREAMBLE ===
