#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: agent (NestJS/TypeScript — no catalog entry; agent fallback)
# Generator version: init-dev-server@1
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.
#
# Why these choices (decision-trace; do not delete):
#   - `set -euo pipefail` not just `-e` — RESEARCH.md Pitfall 4 (silent pipe failures).
#   - `sha256sum` for lockfile hashing — RESEARCH.md "Don't hand-roll" (universal
#     coreutils, no extra dep vs blake3 / git hash-object / md5sum).
#   - Backoff 1s / 2s / 4s — Claude's Discretion per CONTEXT.md (small base, predictable).
#   - Log destination `/tmp/pivota-dev.log` — Open Question #4 resolved (always
#     writable inside Daytona sandboxes; matches existing convention).
#   - Lockfile-sentinel skip combined with INSTALL_PRESENCE_CHECK — RESEARCH.md
#     Pitfall 6 (sentinel survives reboots but install output dirs may not on
#     fresh tmpfs; never skip on a clean directory).
#   - Retry exits with INNER command's last exit code (not a fixed 1) so callers
#     can disambiguate failures from the wrapper.
#   - NestJS: run `prisma migrate deploy` before starting to ensure schema is current.
#   - DATABASE_URL injected by platform (native-sidecar Postgres on localhost:5432).
#   - Redis: falls back to redis://localhost:6379 if REDIS_URL not set.

set -euo pipefail

# === Bash version guard (RESEARCH.md Pitfall 8) ===
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required for 'wait -n'; found ${BASH_VERSION}" >&2
  exit 127
fi

# === D-11.4: tee stdout/stderr to /tmp/pivota-dev.log AND pass through ===
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: agent/nestjs)"

# === ENV preamble: NestJS binds to 0.0.0.0 via app.listen(port, '0.0.0.0') in main.ts ===
export PORT="${PORT:-3000}"
export NODE_ENV="${NODE_ENV:-production}"
export DATABASE_URL="${DATABASE_URL:-postgres://postgres:devpass@localhost:5432/app}"
export REDIS_URL="${REDIS_URL:-redis://localhost:6379}"
export SESSION_SECRET="${SESSION_SECRET:-dev-secret-change-in-prod}"

# === D-11.3: .env.example -> .env transitional copy (until Phase 38) ===
if [[ ! -f .env && -f .env.example ]]; then
  echo "[pivota] copying .env.example -> .env (Phase 38 will replace this hack)"
  cp .env.example .env
fi

# === D-12: idempotent install via lockfile hash + presence check ===
SENTINEL="/tmp/pivota-setup-sentinel"
LOCK_FILE_PATH="package-lock.json"
INSTALL_PRESENCE_CHECK="node_modules/.package-lock.json"
INSTALL_CMD='npm ci --prefer-offline 2>/dev/null || npm install'

run_install() {
  echo "[pivota] running install: $INSTALL_CMD"
  bash -c "$INSTALL_CMD"
}

if [[ -n "$LOCK_FILE_PATH" && -f "$LOCK_FILE_PATH" ]]; then
  CURRENT_HASH=$(sha256sum "$LOCK_FILE_PATH" | cut -d' ' -f1)
  PREVIOUS_HASH=$(cat "$SENTINEL" 2>/dev/null || echo "")

  PRESENCE_OK=1
  if [[ -n "$INSTALL_PRESENCE_CHECK" && ! -e "$INSTALL_PRESENCE_CHECK" ]]; then
    PRESENCE_OK=0
  fi

  if [[ "$CURRENT_HASH" == "$PREVIOUS_HASH" && "$PRESENCE_OK" == "1" ]]; then
    echo "[pivota] lockfile unchanged AND install output present; skipping install"
  else
    if [[ "$PRESENCE_OK" == "0" ]]; then
      echo "[pivota] install output ($INSTALL_PRESENCE_CHECK) missing; install required"
    else
      echo "[pivota] lockfile changed (or first boot); install required"
    fi
    run_install
    echo "$CURRENT_HASH" > "$SENTINEL"
  fi
elif [[ -n "$INSTALL_CMD" ]]; then
  if [[ ! -f "$SENTINEL" ]]; then
    run_install
    touch "$SENTINEL"
  fi
fi

# === Pre-exec: build NestJS and run Prisma migrations ===
echo "[pivota] running prisma migrate deploy..."
npx prisma migrate deploy 2>/dev/null || npx prisma db push --accept-data-loss 2>/dev/null || echo "[pivota] prisma migrate skipped (no migrations dir?)"

echo "[pivota] building NestJS app..."
npm run build

# === D-14: retry loop (3 attempts, exponential backoff 1s / 2s / 4s) ===
EXEC_CMD='node dist/main'
ATTEMPT=1
DELAY=1
while (( ATTEMPT <= 3 )); do
  echo "[pivota] attempt $ATTEMPT: $EXEC_CMD"
  if bash -c "$EXEC_CMD"; then
    echo "[pivota] inner command exited 0; propagating success"
    exit 0
  fi
  EXIT_CODE=$?
  if (( ATTEMPT == 3 )); then
    echo "[pivota] all 3 attempts failed (last exit=$EXIT_CODE); surfacing failure"
    exit "$EXIT_CODE"
  fi
  echo "[pivota] attempt $ATTEMPT failed (exit=$EXIT_CODE); retrying in ${DELAY}s"
  sleep "$DELAY"
  DELAY=$(( DELAY * 2 ))
  ATTEMPT=$(( ATTEMPT + 1 ))
done

# Unreachable, but keep for analyzer happiness
exit 1
# === END PIVOTA PREAMBLE ===
# Below this marker, projects may add custom shutdown / setup logic.
# This region is PRESERVED across regenerations.
