import {
  IsString,
  MaxLength,
  IsUrl,
  IsOptional,
  IsInt,
  IsBoolean,
} from 'class-validator';
import { Type } from 'class-transformer';

export class CreateClientDto {
  @IsString()
  @MaxLength(128)
  name!: string;

  @IsOptional()
  @IsUrl()
  @MaxLength(255)
  url?: string;

  // api_key: 50-char unique token (FRD F11.7); generated by caller or provided
  @IsString()
  @MaxLength(50)
  api_key!: string;

  // contactPerson_id: required FK to people (FRD F11.7)
  @IsInt()
  @Type(() => Number)
  contactPerson_id!: number;

  @IsOptional()
  @IsInt()
  @Type(() => Number)
  contactMethod_id?: number;

  // active: defaults true; set false to revoke access (FRD F11.7)
  @IsOptional()
  @IsBoolean()
  active?: boolean = true;
}
